version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_web
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/app

volumes:
  postgres_data:
