# Generated by Django 5.1.7 on 2025-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_user_managers_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
