# Generated by Django 5.1.7 on 2025-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
