# Generated by Django 5.1.7 on 2025-03-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_document_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.role'),
        ),
    ]
