# Generated by Django 5.1.7 on 2025-04-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_rename_uploaded_at_document_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='unique_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
