# Generated by Django 5.1.7 on 2025-04-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_document_unique_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='unique_filename',
        ),
    ]
