# Generated by Django 5.2 on 2025-04-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_documenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={},
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
