# Generated by Django 5.1.7 on 2025-03-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_path',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
